# Generated by Django 3.0 on 2020-04-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=10, null=True)),
                ('cname', models.CharField(max_length=30)),
                ('enname', models.CharField(max_length=50, null=True)),
                ('releasetime', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=10)),
                ('actors', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=5)),
                ('introduction', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Heat_movies',
            fields=[
                ('top_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=10, null=True)),
                ('cname', models.CharField(max_length=30)),
                ('enname', models.CharField(max_length=50, null=True)),
                ('releasetime', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=20)),
                ('actors', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesForm',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=10, null=True)),
                ('cname', models.CharField(max_length=30)),
                ('enname', models.CharField(max_length=50, null=True)),
                ('releasetime', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=10)),
                ('actors', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=5)),
                ('introduction', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'MoviesForm',
            },
        ),
        migrations.CreateModel(
            name='Top_movies',
            fields=[
                ('top_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=10, null=True)),
                ('cname', models.CharField(max_length=30)),
                ('enname', models.CharField(max_length=50, null=True)),
                ('score_integer', models.CharField(max_length=3)),
                ('score_fraction', models.CharField(max_length=3)),
            ],
        ),
    ]
