# Generated by Django 3.0 on 2020-04-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesform',
            name='actors',
            field=models.CharField(max_length=50),
        ),
    ]
