# Generated by Django 3.0 on 2020-04-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0002_auto_20200404_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=5, unique=True)),
                ('movie', models.ManyToManyField(to='showimage.MoviesForm')),
            ],
            options={
                'db_table': 'Kind',
            },
        ),
    ]
