# Generated by Django 3.0 on 2020-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0004_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation_movies',
            fields=[
                ('top_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=10, null=True)),
                ('actors', models.CharField(max_length=30)),
            ],
        ),
    ]
