# Generated by Django 3.0 on 2020-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0006_animation_movies_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation_movies',
            name='cname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='animation_movies',
            name='filename',
            field=models.CharField(max_length=10),
        ),
    ]
