# Generated by Django 3.0 on 2020-04-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0007_auto_20200405_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation_movies',
            old_name='actors',
            new_name='director',
        ),
    ]
