# Generated by Django 3.0 on 2020-04-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0008_auto_20200405_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_movies',
        ),
    ]
