# Generated by Django 3.0 on 2020-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0009_delete_all_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_movies',
            fields=[
                ('top_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Ranking_movies',
            },
        ),
    ]
