# Generated by Django 3.0 on 2020-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0011_auto_20200412_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking_movies',
            name='actors',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ranking_movies',
            name='director',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
