# Generated by Django 3.0 on 2020-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0012_auto_20200412_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation_movies',
            name='actors',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
