# Generated by Django 3.0 on 2020-04-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0013_animation_movies_actors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking_movies',
        ),
    ]
