# Generated by Django 3.0 on 2020-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showimage', '0015_ranking_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking_movies',
            name='actors',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
